### ISSUE TITLE
Issue: Enhance Email Validation Function and Add Tests

### ISSUE THREAD

**Issue by Colin-Stark** [Colin-Stark/eventServer#1]
# Refactor `emailCheck` Function for Improved Validation and Edge Case Handling

## Description:
Refactor the `emailCheck` function to improve email validation, ensuring it handles edge cases correctly, particularly for `@myseneca.ca` and `@senecapolytechnic.ca`.

### Current Behavior:
- Email must contain an `@` sign.
- Email must contain a dot (`.`).
- Email must end with `@myseneca.ca` or `@senecapolytechnic.ca`.
- If the email ends with `@senecapolytechnic.ca`, it requires a dot in the local part, rejecting multiple dots.

### Expected Behavior:
The function should return `true` for valid emails and `false` for invalid ones.

### Valid Emails:
- `firstname.lastname@senecapolytechnic.ca`
- `student.name@senecapolytechnic.ca`
- `user@myseneca.ca`

### Invalid Emails:
- `firstname@myseneca.ca` (invalid, local part contains a dot)
- `username@senecapolytechnic.ca` (no dot in local part)
- `user..name@senecapolytechnic.ca` (multiple dots)
- `user@example.com` (wrong domain)

### Tasks:
1. **Refactor `emailCheck` function** to meet the conditions above.
2. **Add Tests for Edge Cases**:
   - Test valid emails.
   - Test invalid formats (missing `@`, missing `.`, etc.).
   - Test domain-specific rules (`@myseneca.ca`, `@senecapolytechnic.ca`).
   - Test for multiple dots or missing dot in local part.

### How to Contribute:
1. Fork the repo and create a branch.
2. Add test cases based on the edge cases above.
3. Run `npm test` to ensure all tests pass.
4. If the test passes, commit your changes. If it fails, GitHub Actions will flag the failure.
5. If the function passes an invalid email, leave a comment with a detailed explanation and example.
6. Submit a PR once all tests pass.

### Example Test Suite:
Refer to [emailCheck test cases](https://github.com/Colin-Stark/eventServer/blob/main/test/emailCheck.test.js).

### Notes:
Ensure changes don't break existing functionality. If you find edge cases where the function behaves incorrectly, provide examples and explanations in comments.

**Comment by FelipeLohan** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by syamjir** [comment]
Hi @Colin-Stark,

Please review the pull request.

Thank you!

**Comment by Colin-Stark** [comment]
> I would like to work on this issue. Could you please assign it to me?

You can fork the repository and make changes then do a pull request, I will review it and let you know. It is open to everyone

**Comment by syamjir** [comment]
@Colin-Stark, one test is failing due to the absence of an .env file with the PORT variable. I am checking this and realized the file is missing.
