### ISSUE TITLE
Enhancement Request: Improve passwordMatch Function

### ISSUE THREAD

**Issue by Colin-Stark** [Colin-Stark/eventServer#5]
We are currently using a basic implementation of the passwordMatch function to compare passwords and ensure they meet certain criteria, but there may be opportunities to improve its efficiency, security, or flexibility. This issue invites the community to propose and implement enhancements to this function if they have a better approach.

# Contribution Guidelines
- Fork the repository and create a new branch for your changes.
- Make sure to run the tests locally and ensure they pass before submitting a pull request.
- Add or modify tests to cover any new functionality or behavior introduced.
- Provide a detailed description of any changes made in the pull request.

**Comment by SujayDas1999** [comment]
Hi @Colin-Stark 
Could you please explain in brief what are the current rules that we follow to match password ?

**Comment by Colin-Stark** [comment]
Just making sure that password and confirm password match

The minimum length is 8 and maximum length is 20

**Comment by SujayDas1999** [comment]
You can assign this to me
